Update _config.yml
Deprecation updates -- fix config variables, etc. Error message:

Deprecation: The 'layouts' configuration option has been renamed to 'layouts_dir'. Please update your config file accordingly.
       Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
       Deprecation: Please change 'use_coderay' to 'enable_coderay' in your configuration file.
             Error: You're using the 'maruku' Markdown processor, which has been removed as of 3.0.0. We recommend you switch to Kramdown. To do this, replace `markdown: maruku` with `markdown: kramdown` in your `_config.yml` file.